[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
truth_project = "FFL71XjBkjq5gce7EtpB7Wa5p8qnRNueLKSzM4tkEMoc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
